export const TwgData = [
    {
        id:1,
        img: '/assets/Photos/TWG/1.jpg',
        alt: "Alyssa Ashley Maturan - Logistics Head ",
        name: "Alyssa Ashley Maturan",
        position: "Logistics Head",
    },
    {
        id:2,
        img: '/assets/Photos/TWG/2.jpg',
        alt: "Amie Campomanes - Productions Director",
        name: "Amie Campomanes",
        position: "Productions Director",
    },

    {
        id:3,
        img: '/assets/Photos/TWG/3.jpg',
        alt: "Angas, Aldriena Thehani - Assistant Coordinator",
        name: "Angas, Aldriena Thehani",
        position: "Assistant Coordinator",
    },
    {
        id:4,
        img: '/assets/Photos/TWG/4.jpg',
        alt: "Banuelos, Elijah James - Deputy for Creatives",
        name: "Banuelos, Elijah James",
        position: "Deputy for Creatives",
    },
    {
        id:5,
        img: '/assets/Photos/TWG/5.jpg',
        alt: "Cequina, Alanis Mari - Deputy for Accommodations",
        name: "Cequina, Alanis Mari",
        position: "Deputy for Accommodations",
    },
    {
        id:6,
        img: '/assets/Photos/TWG/6.jpg',
        alt: "Chris Laurence Tungpalan - Physical Oversight Officer",
        name: "Chris Laurence Tungpalan",
        position: "Physical Oversight Officer",
    },
    {
        id:7,
        img: '/assets/Photos/TWG/7.jpg',
        alt: "Chyna Marie Legaspina - Deputy for Meals",
        name: "Chyna Marie Legaspina",
        position: "Deputy for Meals",
    },
    {
        id:8,
        img: '/assets/Photos/TWG/8.jpg',
        alt: "Jhoana Alilin - Assistant Communications Director",
        name: "Jhoana Alilin",
        position: "Assistant Communications Director",
    },
    {
        id:9,
        img: '/assets/Photos/TWG/9.jpg',
        alt: "Jin Lorenz Tinitigan - Overall Coordinator",
        name: "Jin Lorenz Tinitigan",
        position: "Overall Coordinator",
    },
    {
        id:10,
        img: '/assets/Photos/TWG/10.jpg',
        alt: "Joanna Danielle Ang - Quality Control Officer",
        name: "Joanna Danielle Ang",
        position: "Quality Control Officer",
    },
    {
        id:11,
        img: '/assets/Photos/TWG/11.jpg',
        alt: "Kent Ongcoy - Communications Director",
        name: "Kent Ongcoy",
        position: "Communications Director",
    },
    {
        id:12,
        img: '/assets/Photos/TWG/12.jpg',
        alt: "Kenth Warren S. Cervantes - Head for Creatives",
        name: "Kenth Warren S. Cervantes",
        position: "Head for Creatives",
    },
    {
        id:13,
        img: '/assets/Photos/TWG/13.jpg',
        alt: "Olbes, Euneece Angella - Non-Competitive Events Coordinator",
        name: "Olbes, Euneece Angella",
        position: "Non-Competitive Events Coordinator",
    },
    {
        id:14,
        img: '/assets/Photos/TWG/14.jpeg',
        alt: "Orig, Mary Juliet - Tabulations Head",
        name: "Orig, Mary Juliet",
        position: "Tabulations Head",
    },
    {
        id:15,
        img: '/assets/Photos/TWG/15.jpg',
        alt: "Patricia Ivan Marie Bitana - Sponsorships Head",
        name: "Patricia Ivan Marie Bitana",
        position: "Sponsorships Head",
    },
    {
        id:16,
        img: '/assets/Photos/TWG/16.jpg',
        alt: "Salonga, Jette Marrionne - Stage and Designs Head",
        name: "Salonga, Jette Marrionne",
        position: "Stage and Designs Head ",
    },
    {
        id:17,
        img: '/assets/Photos/TWG/17.jpg',
        alt: "Sapsal, John Paul - Deputy Secretary",
        name: "Sapsal, John Paul",
        position: "Deputy Secretary",
    },
    {
        id:18,
        img: '/assets/Photos/TWG/18.jpg',
        alt: "Tarnate, Marion James - Finance Head",
        name: "Tarnate, Marion James",
        position: "Finance Head",
    },
    {
        id:19,
        img: '/assets/Photos/TWG/19.jpg',
        alt: "Tobias, Adrianne - Secretariat Head",
        name: "Tobias, Adrianne",
        position: "Secretariat Head",
    },
    {
        id:20,
        img: '/assets/Photos/TWG/20.jpg',
        alt: "Torreon, Karlo Alessandro - External Liaison Officer",
        name: "Torreon, Karlo Alessandro",
        position: "External Liaison Officer",
    },
    {
        id:21,
        img: '/assets/Photos/TWG/21.jpg',
        alt: "Verallo, Rholien Rhoi - Physical Oversight Head",
        name: "Verallo, Rholien Rhoi",
        position: "Physical Oversight Head",
    },

]